// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1gGSeV1A_SJuxZgJSkoyDxS0ATKU4zw',
    appId: '1:980847129235:web:e0427fe89fc484c36a5366',
    messagingSenderId: '980847129235',
    projectId: 'fultter-startter',
    authDomain: 'fultter-startter.firebaseapp.com',
    storageBucket: 'fultter-startter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA41PLJZNOwXydrMwqI1tLTObXRmISaAlc',
    appId: '1:980847129235:android:dbbdff8d35bc81246a5366',
    messagingSenderId: '980847129235',
    projectId: 'fultter-startter',
    storageBucket: 'fultter-startter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiRSr2DRD4fXQYcy7oSyJRNBBTsxKudOY',
    appId: '1:980847129235:ios:bf8d72556c56d8476a5366',
    messagingSenderId: '980847129235',
    projectId: 'fultter-startter',
    storageBucket: 'fultter-startter.appspot.com',
    iosBundleId: 'com.example.firebaseexample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiRSr2DRD4fXQYcy7oSyJRNBBTsxKudOY',
    appId: '1:980847129235:ios:7097e0689c1c8c346a5366',
    messagingSenderId: '980847129235',
    projectId: 'fultter-startter',
    storageBucket: 'fultter-startter.appspot.com',
    iosBundleId: 'com.example.firebaseexample.RunnerTests',
  );
}
